-- Inserir ou atualizar características da raça Boer diretamente no banco
INSERT INTO "RacaCaracteristicas" (
    id,
    tipo,
    raca,
    origem,
    "pesoNascer",
    "peso10Meses",
    "pesoMachoAdulto",
    "pesoFemeaAdulta",
    "maturidadeSexual",
    "femeaTemLeite",
    "periodoGestacao",
    "quantidadeCabritosParto",
    "abatePrecoceDias",
    "abateConvencionalDias",
    "abateTardioDiasMin",
    "abateTardioDiasMax",
    "pelagemCouro",
    "maxFemeasPorMacho",
    "femeasPorMachoIdeal",
    "ganhoPesoDiaGramas",
    "percentualGorduraCarne",
    "indiceColesterol",
    "indiceGorduraSaturada",
    "indiceCalorias",
    "carneMacia",
    "carneSaborosa",
    "carneSucculenta"
) VALUES (
    gen_random_uuid(),
    'Caprino',
    'Boer',
    'África do Sul',
    3.5,
    35.0,
    110.0,
    80.0,
    6,
    true,
    150,
    2.5,
    90,
    165,
    180,
    360,
    'curto',
    50,
    33,
    350.0,
    2.5,
    'baixo',
    'baixo',
    'baixo',
    true,
    true,
    true
)
ON CONFLICT (tipo, raca) 
DO UPDATE SET
    origem = EXCLUDED.origem,
    "pesoNascer" = EXCLUDED."pesoNascer",
    "peso10Meses" = EXCLUDED."peso10Meses",
    "pesoMachoAdulto" = EXCLUDED."pesoMachoAdulto",
    "pesoFemeaAdulta" = EXCLUDED."pesoFemeaAdulta",
    "maturidadeSexual" = EXCLUDED."maturidadeSexual",
    "femeaTemLeite" = EXCLUDED."femeaTemLeite",
    "periodoGestacao" = EXCLUDED."periodoGestacao",
    "quantidadeCabritosParto" = EXCLUDED."quantidadeCabritosParto",
    "abatePrecoceDias" = EXCLUDED."abatePrecoceDias",
    "abateConvencionalDias" = EXCLUDED."abateConvencionalDias",
    "abateTardioDiasMin" = EXCLUDED."abateTardioDiasMin",
    "abateTardioDiasMax" = EXCLUDED."abateTardioDiasMax",
    "pelagemCouro" = EXCLUDED."pelagemCouro",
    "maxFemeasPorMacho" = EXCLUDED."maxFemeasPorMacho",
    "femeasPorMachoIdeal" = EXCLUDED."femeasPorMachoIdeal",
    "ganhoPesoDiaGramas" = EXCLUDED."ganhoPesoDiaGramas",
    "percentualGorduraCarne" = EXCLUDED."percentualGorduraCarne",
    "indiceColesterol" = EXCLUDED."indiceColesterol",
    "indiceGorduraSaturada" = EXCLUDED."indiceGorduraSaturada",
    "indiceCalorias" = EXCLUDED."indiceCalorias",
    "carneMacia" = EXCLUDED."carneMacia",
    "carneSaborosa" = EXCLUDED."carneSaborosa",
    "carneSucculenta" = EXCLUDED."carneSucculenta";