const { PrismaClient } = require("@prisma/client");
const { PrismaPg } = require("@prisma/adapter-pg");
const { Pool } = require("pg");

const connectionString =
  process.env.DATABASE_URL ||
  "postgresql://neondb_owner:npg_im83ophwtcLV@ep-muddy-snow-ac20yxgt-pooler.sa-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require";

const pool = new Pool({ connectionString });
const adapter = new PrismaPg(pool);

const prisma = new PrismaClient({ adapter });

async function main() {
  // Lista de raças com características detalhadas
  const racasCaracteristicas = [
    // Caprinos
    {
      tipo: "Caprino",
      raca: "Boer",
      origem: "África do Sul",
      pesoNascer: 3.5,
      peso10Meses: 35.0,
      pesoMachoAdulto: 110.0,
      pesoFemeaAdulta: 80.0,
      maturidadeSexual: 6,
      femeaTemLeite: true,
      periodoGestacao: 150,
      quantidadeCabritosParto: 2.5,
      abatePrecoceDias: 90,
      abateConvencionalDias: 165,
      abateTardioDiasMin: 180,
      abateTardioDiasMax: 360,
      pelagemCouro: "curto",
      maxFemeasPorMacho: 50,
      femeasPorMachoIdeal: 33,
      ganhoPesoDiaGramas: 350.0,
      percentualGorduraCarne: 2.5,
      indiceColesterol: "baixo",
      indiceGorduraSaturada: "baixo",
      indiceCalorias: "baixo",
      carneMacia: true,
      carneSaborosa: true,
      carneSucculenta: true,
      fasesGanhoPeso: [
        {
          id: 1,
          nome: "Cabrito",
          mesInicio: 0,
          mesFim: 6,
          pesoMedioInicioMacho: 4,
          pesoMedioInicioFemea: 4,
          pesoMedioFimMacho: 40,
          pesoMedioFimFemea: 40,
        },
        {
          id: 2,
          nome: "Novilho",
          mesInicio: 7,
          mesFim: 13,
          pesoMedioInicioMacho: 40,
          pesoMedioInicioFemea: 40,
          pesoMedioFimMacho: 80,
          pesoMedioFimFemea: 70,
        },
        {
          id: 3,
          nome: "Jovem Adulto",
          mesInicio: 14,
          mesFim: 24,
          pesoMedioInicioMacho: 80,
          pesoMedioInicioFemea: 70,
          pesoMedioFimMacho: 100,
          pesoMedioFimFemea: 90,
        },
        {
          id: 4,
          nome: "Adulto",
          mesInicio: 25,
          mesFim: 96,
          pesoMedioInicioMacho: 100,
          pesoMedioInicioFemea: 90,
          pesoMedioFimMacho: 110,
          pesoMedioFimFemea: 100,
        },
        {
          nome: "Senil Veterano",
          mesInicio: 97,
          mesFim: 250,
          pesoMedioInicioMacho: 110,
          pesoMedioInicioFemea: 100,
          pesoMedioFimMacho: 110,
          pesoMedioFimFemea: 100,
        },
      ],
    },
    {
      tipo: "Caprino",
      raca: "Anglo-Nubiana",
      origem: "Inglaterra/Egito",
      pesoNascer: 4.0,
      peso10Meses: 30.0,
      pesoMachoAdulto: 90.0,
      pesoFemeaAdulta: 65.0,
      maturidadeSexual: 8,
      femeaTemLeite: true,
      periodoGestacao: 150,
      quantidadeCabritosParto: 2.0,
      abatePrecoceDias: 120,
      abateConvencionalDias: 180,
      abateTardioDiasMin: 200,
      abateTardioDiasMax: 400,
      pelagemCouro: "curto",
      maxFemeasPorMacho: 40,
      femeasPorMachoIdeal: 25,
      ganhoPesoDiaGramas: 280.0,
      percentualGorduraCarne: 3.0,
      indiceColesterol: "baixo",
      indiceGorduraSaturada: "baixo",
      indiceCalorias: "baixo",
      carneMacia: true,
      carneSaborosa: true,
      carneSucculenta: true,
      fasesGanhoPeso: [
        {
          id: 1,
          nome: "Cabrito",
          mesInicio: 0,
          mesFim: 6,
          pesoMedioInicioMacho: 4,
          pesoMedioInicioFemea: 4,
          pesoMedioFimMacho: 35,
          pesoMedioFimFemea: 32,
        },
        {
          id: 2,
          nome: "Jovem",
          mesInicio: 7,
          mesFim: 12,
          pesoMedioInicioMacho: 35,
          pesoMedioInicioFemea: 32,
          pesoMedioFimMacho: 65,
          pesoMedioFimFemea: 55,
        },
        {
          id: 3,
          nome: "Adulto",
          mesInicio: 13,
          mesFim: 96,
          pesoMedioInicioMacho: 65,
          pesoMedioInicioFemea: 55,
          pesoMedioFimMacho: 90,
          pesoMedioFimFemea: 65,
        },
        {
          nome: "Veterano",
          mesInicio: 97,
          mesFim: 200,
          pesoMedioInicioMacho: 90,
          pesoMedioInicioFemea: 65,
          pesoMedioFimMacho: 90,
          pesoMedioFimFemea: 65,
        },
      ],
    },
    {
      tipo: "Caprino",
      raca: "Saanen",
      origem: "Suíça",
      pesoNascer: 3.8,
      peso10Meses: 32.0,
      pesoMachoAdulto: 85.0,
      pesoFemeaAdulta: 60.0,
      maturidadeSexual: 7,
      femeaTemLeite: true,
      periodoGestacao: 150,
      quantidadeCabritosParto: 2.2,
      abatePrecoceDias: 100,
      abateConvencionalDias: 170,
      abateTardioDiasMin: 190,
      abateTardioDiasMax: 380,
      pelagemCouro: "curto",
      maxFemeasPorMacho: 45,
      femeasPorMachoIdeal: 30,
      ganhoPesoDiaGramas: 260.0,
      percentualGorduraCarne: 2.8,
      indiceColesterol: "baixo",
      indiceGorduraSaturada: "baixo",
      indiceCalorias: "baixo",
      carneMacia: true,
      carneSaborosa: true,
      carneSucculenta: true,
      fasesGanhoPeso: [
        {
          id: 1,
          nome: "Cabrito",
          mesInicio: 0,
          mesFim: 6,
          pesoMedioInicioMacho: 4,
          pesoMedioInicioFemea: 4,
          pesoMedioFimMacho: 32,
          pesoMedioFimFemea: 30,
        },
        {
          id: 2,
          nome: "Jovem",
          mesInicio: 7,
          mesFim: 12,
          pesoMedioInicioMacho: 32,
          pesoMedioInicioFemea: 30,
          pesoMedioFimMacho: 60,
          pesoMedioFimFemea: 50,
        },
        {
          id: 3,
          nome: "Adulto",
          mesInicio: 13,
          mesFim: 96,
          pesoMedioInicioMacho: 60,
          pesoMedioInicioFemea: 50,
          pesoMedioFimMacho: 85,
          pesoMedioFimFemea: 60,
        },
        {
          nome: "Veterano",
          mesInicio: 97,
          mesFim: 200,
          pesoMedioInicioMacho: 85,
          pesoMedioInicioFemea: 60,
          pesoMedioFimMacho: 85,
          pesoMedioFimFemea: 60,
        },
      ],
    },
    {
      tipo: "Ovino",
      raca: "Dorper",
      origem: "África do Sul",
      pesoNascer: 4.2,
      peso10Meses: 45.0,
      pesoMachoAdulto: 120.0,
      pesoFemeaAdulta: 85.0,
      maturidadeSexual: 8,
      femeaTemLeite: true,
      periodoGestacao: 150,
      quantidadeCabritosParto: 1.8,
      abatePrecoceDias: 100,
      abateConvencionalDias: 180,
      abateTardioDiasMin: 200,
      abateTardioDiasMax: 450,
      pelagemCouro: "misto",
      maxFemeasPorMacho: 40,
      femeasPorMachoIdeal: 25,
      ganhoPesoDiaGramas: 380.0,
      percentualGorduraCarne: 3.2,
      indiceColesterol: "baixo",
      indiceGorduraSaturada: "baixo",
      indiceCalorias: "médio",
      carneMacia: true,
      carneSaborosa: true,
      carneSucculenta: true,
      fasesGanhoPeso: [
        {
          id: 1,
          nome: "Cordeiro",
          mesInicio: 0,
          mesFim: 6,
          pesoMedioInicioMacho: 4,
          pesoMedioInicioFemea: 4,
          pesoMedioFimMacho: 45,
          pesoMedioFimFemea: 40,
        },
        {
          id: 2,
          nome: "Borrego",
          mesInicio: 7,
          mesFim: 12,
          pesoMedioInicioMacho: 45,
          pesoMedioInicioFemea: 40,
          pesoMedioFimMacho: 80,
          pesoMedioFimFemea: 65,
        },
        {
          id: 3,
          nome: "Adulto",
          mesInicio: 13,
          mesFim: 96,
          pesoMedioInicioMacho: 80,
          pesoMedioInicioFemea: 65,
          pesoMedioFimMacho: 120,
          pesoMedioFimFemea: 85,
        },
        {
          nome: "Veterano",
          mesInicio: 97,
          mesFim: 180,
          pesoMedioInicioMacho: 120,
          pesoMedioInicioFemea: 85,
          pesoMedioFimMacho: 120,
          pesoMedioFimFemea: 85,
        },
      ],
    },
    {
      tipo: "Ovino",
      raca: "Santa Inês",
      origem: "Brasil",
      pesoNascer: 3.5,
      peso10Meses: 35.0,
      pesoMachoAdulto: 80.0,
      pesoFemeaAdulta: 55.0,
      maturidadeSexual: 8,
      femeaTemLeite: true,
      periodoGestacao: 150,
      quantidadeCabritosParto: 1.5,
      abatePrecoceDias: 120,
      abateConvencionalDias: 200,
      abateTardioDiasMin: 220,
      abateTardioDiasMax: 400,
      pelagemCouro: "curto",
      maxFemeasPorMacho: 35,
      femeasPorMachoIdeal: 20,
      ganhoPesoDiaGramas: 240.0,
      percentualGorduraCarne: 2.8,
      indiceColesterol: "baixo",
      indiceGorduraSaturada: "baixo",
      indiceCalorias: "baixo",
      carneMacia: true,
      carneSaborosa: true,
      carneSucculenta: true,
      fasesGanhoPeso: [
        {
          id: 1,
          nome: "Cordeiro",
          mesInicio: 0,
          mesFim: 6,
          pesoMedioInicioMacho: 4,
          pesoMedioInicioFemea: 4,
          pesoMedioFimMacho: 35,
          pesoMedioFimFemea: 32,
        },
        {
          id: 2,
          nome: "Borrego",
          mesInicio: 7,
          mesFim: 12,
          pesoMedioInicioMacho: 35,
          pesoMedioInicioFemea: 32,
          pesoMedioFimMacho: 60,
          pesoMedioFimFemea: 45,
        },
        {
          id: 3,
          nome: "Adulto",
          mesInicio: 13,
          mesFim: 96,
          pesoMedioInicioMacho: 60,
          pesoMedioInicioFemea: 45,
          pesoMedioFimMacho: 80,
          pesoMedioFimFemea: 55,
        },
        {
          nome: "Veterano",
          mesInicio: 97,
          mesFim: 180,
          pesoMedioInicioMacho: 80,
          pesoMedioInicioFemea: 55,
          pesoMedioFimMacho: 80,
          pesoMedioFimFemea: 55,
        },
      ],
    },
    {
      tipo: "Bovino",
      raca: "Nelore",
      origem: "Índia/Brasil",
      pesoNascer: 32.0,
      peso10Meses: 280.0,
      pesoMachoAdulto: 800.0,
      pesoFemeaAdulta: 550.0,
      maturidadeSexual: 24,
      femeaTemLeite: true,
      periodoGestacao: 285,
      quantidadeCabritosParto: 1.0,
      abatePrecoceDias: 450,
      abateConvencionalDias: 720,
      abateTardioDiasMin: 900,
      abateTardioDiasMax: 1800,
      pelagemCouro: "curto",
      maxFemeasPorMacho: 30,
      femeasPorMachoIdeal: 20,
      ganhoPesoDiaGramas: 1200.0,
      percentualGorduraCarne: 5.0,
      indiceColesterol: "médio",
      indiceGorduraSaturada: "médio",
      indiceCalorias: "alto",
      carneMacia: true,
      carneSaborosa: true,
      carneSucculenta: true,
      fasesGanhoPeso: [
        {
          id: 1,
          nome: "Bezerro",
          mesInicio: 0,
          mesFim: 12,
          pesoMedioInicioMacho: 32,
          pesoMedioInicioFemea: 30,
          pesoMedioFimMacho: 280,
          pesoMedioFimFemea: 250,
        },
        {
          id: 2,
          nome: "Novilho",
          mesInicio: 13,
          mesFim: 30,
          pesoMedioInicioMacho: 280,
          pesoMedioInicioFemea: 250,
          pesoMedioFimMacho: 550,
          pesoMedioFimFemea: 450,
        },
        {
          id: 3,
          nome: "Adulto",
          mesInicio: 31,
          mesFim: 120,
          pesoMedioInicioMacho: 550,
          pesoMedioInicioFemea: 450,
          pesoMedioFimMacho: 800,
          pesoMedioFimFemea: 550,
        },
        {
          nome: "Veterano",
          mesInicio: 121,
          mesFim: 240,
          pesoMedioInicioMacho: 800,
          pesoMedioInicioFemea: 550,
          pesoMedioFimMacho: 800,
          pesoMedioFimFemea: 550,
        },
      ],
    },
    {
      tipo: "Bovino",
      raca: "Angus",
      origem: "Escócia",
      pesoNascer: 35.0,
      peso10Meses: 320.0,
      pesoMachoAdulto: 900.0,
      pesoFemeaAdulta: 650.0,
      maturidadeSexual: 18,
      femeaTemLeite: true,
      periodoGestacao: 285,
      quantidadeCabritosParto: 1.0,
      abatePrecoceDias: 400,
      abateConvencionalDias: 650,
      abateTardioDiasMin: 800,
      abateTardioDiasMax: 1600,
      pelagemCouro: "curto",
      maxFemeasPorMacho: 25,
      femeasPorMachoIdeal: 15,
      ganhoPesoDiaGramas: 1400.0,
      percentualGorduraCarne: 6.5,
      indiceColesterol: "médio",
      indiceGorduraSaturada: "alto",
      indiceCalorias: "alto",
      carneMacia: true,
      carneSaborosa: true,
      carneSucculenta: true,
      fasesGanhoPeso: [
        {
          id: 1,
          nome: "Bezerro",
          mesInicio: 0,
          mesFim: 12,
          pesoMedioInicioMacho: 35,
          pesoMedioInicioFemea: 32,
          pesoMedioFimMacho: 320,
          pesoMedioFimFemea: 280,
        },
        {
          id: 2,
          nome: "Novilho",
          mesInicio: 13,
          mesFim: 24,
          pesoMedioInicioMacho: 320,
          pesoMedioInicioFemea: 280,
          pesoMedioFimMacho: 650,
          pesoMedioFimFemea: 520,
        },
        {
          id: 3,
          nome: "Adulto",
          mesInicio: 25,
          mesFim: 120,
          pesoMedioInicioMacho: 650,
          pesoMedioInicioFemea: 520,
          pesoMedioFimMacho: 900,
          pesoMedioFimFemea: 650,
        },
        {
          nome: "Veterano",
          mesInicio: 121,
          mesFim: 200,
          pesoMedioInicioMacho: 900,
          pesoMedioInicioFemea: 650,
          pesoMedioFimMacho: 900,
          pesoMedioFimFemea: 650,
        },
      ],
    },
    {
      tipo: "Suíno",
      raca: "Large White",
      origem: "Inglaterra",
      pesoNascer: 1.4,
      peso10Meses: 180.0,
      pesoMachoAdulto: 350.0,
      pesoFemeaAdulta: 300.0,
      maturidadeSexual: 6,
      femeaTemLeite: true,
      periodoGestacao: 114,
      quantidadeCabritosParto: 11.0,
      abatePrecoceDias: 90,
      abateConvencionalDias: 180,
      abateTardioDiasMin: 200,
      abateTardioDiasMax: 300,
      pelagemCouro: "curto",
      maxFemeasPorMacho: 15,
      femeasPorMachoIdeal: 10,
      ganhoPesoDiaGramas: 800.0,
      percentualGorduraCarne: 8.0,
      indiceColesterol: "alto",
      indiceGorduraSaturada: "alto",
      indiceCalorias: "alto",
      carneMacia: true,
      carneSaborosa: true,
      carneSucculenta: true,
      fasesGanhoPeso: [
        {
          id: 1,
          nome: "Leitão",
          mesInicio: 0,
          mesFim: 2,
          pesoMedioInicioMacho: 1,
          pesoMedioInicioFemea: 1,
          pesoMedioFimMacho: 25,
          pesoMedioFimFemea: 22,
        },
        {
          id: 2,
          nome: "Crescimento",
          mesInicio: 3,
          mesFim: 6,
          pesoMedioInicioMacho: 25,
          pesoMedioInicioFemea: 22,
          pesoMedioFimMacho: 100,
          pesoMedioFimFemea: 90,
        },
        {
          id: 3,
          nome: "Terminação",
          mesInicio: 7,
          mesFim: 12,
          pesoMedioInicioMacho: 100,
          pesoMedioInicioFemea: 90,
          pesoMedioFimMacho: 250,
          pesoMedioFimFemea: 220,
        },
        {
          nome: "Adulto",
          mesInicio: 13,
          mesFim: 60,
          pesoMedioInicioMacho: 250,
          pesoMedioInicioFemea: 220,
          pesoMedioFimMacho: 350,
          pesoMedioFimFemea: 300,
        },
      ],
    },
    {
      tipo: "Equino",
      raca: "Quarto de Milha",
      origem: "Estados Unidos",
      pesoNascer: 45.0,
      peso10Meses: 380.0,
      pesoMachoAdulto: 550.0,
      pesoFemeaAdulta: 480.0,
      maturidadeSexual: 24,
      femeaTemLeite: true,
      periodoGestacao: 340,
      quantidadeCabritosParto: 1.0,
      abatePrecoceDias: 0,
      abateConvencionalDias: 0,
      abateTardioDiasMin: 0,
      abateTardioDiasMax: 0,
      pelagemCouro: "curto",
      maxFemeasPorMacho: 20,
      femeasPorMachoIdeal: 12,
      ganhoPesoDiaGramas: 1100.0,
      percentualGorduraCarne: 0.0,
      indiceColesterol: "baixo",
      indiceGorduraSaturada: "baixo",
      indiceCalorias: "baixo",
      carneMacia: false,
      carneSaborosa: false,
      carneSucculenta: false,
      fasesGanhoPeso: [
        {
          id: 1,
          nome: "Potro",
          mesInicio: 0,
          mesFim: 12,
          pesoMedioInicioMacho: 45,
          pesoMedioInicioFemea: 42,
          pesoMedioFimMacho: 380,
          pesoMedioFimFemea: 350,
        },
        {
          id: 2,
          nome: "Jovem",
          mesInicio: 13,
          mesFim: 36,
          pesoMedioInicioMacho: 380,
          pesoMedioInicioFemea: 350,
          pesoMedioFimMacho: 500,
          pesoMedioFimFemea: 440,
        },
        {
          id: 3,
          nome: "Adulto",
          mesInicio: 37,
          mesFim: 240,
          pesoMedioInicioMacho: 500,
          pesoMedioInicioFemea: 440,
          pesoMedioFimMacho: 550,
          pesoMedioFimFemea: 480,
        },
        {
          nome: "Veterano",
          mesInicio: 241,
          mesFim: 360,
          pesoMedioInicioMacho: 550,
          pesoMedioInicioFemea: 480,
          pesoMedioFimMacho: 550,
          pesoMedioFimFemea: 480,
        },
      ],
    },
    {
      tipo: "Caprino",
      raca: "Alpina",
      origem: "França",
      pesoNascer: 3.8,
      peso10Meses: 32.0,
      pesoMachoAdulto: 75.0,
      pesoFemeaAdulta: 55.0,
      maturidadeSexual: 7,
      femeaTemLeite: true,
      periodoGestacao: 150,
      quantidadeCabritosParto: 2.3,
      abatePrecoceDias: 110,
      abateConvencionalDias: 180,
      abateTardioDiasMin: 200,
      abateTardioDiasMax: 400,
      pelagemCouro: "médio",
      maxFemeasPorMacho: 40,
      femeasPorMachoIdeal: 25,
      ganhoPesoDiaGramas: 250.0,
      percentualGorduraCarne: 2.8,
      indiceColesterol: "baixo",
      indiceGorduraSaturada: "baixo",
      indiceCalorias: "baixo",
      carneMacia: true,
      carneSaborosa: true,
      carneSucculenta: true,
      fasesGanhoPeso: [
        {
          id: 1,
          nome: "Cabrito",
          mesInicio: 0,
          mesFim: 6,
          pesoMedioInicioMacho: 4,
          pesoMedioInicioFemea: 4,
          pesoMedioFimMacho: 30,
          pesoMedioFimFemea: 28,
        },
        {
          id: 2,
          nome: "Jovem",
          mesInicio: 7,
          mesFim: 12,
          pesoMedioInicioMacho: 30,
          pesoMedioInicioFemea: 28,
          pesoMedioFimMacho: 55,
          pesoMedioFimFemea: 45,
        },
        {
          id: 3,
          nome: "Adulto",
          mesInicio: 13,
          mesFim: 96,
          pesoMedioInicioMacho: 55,
          pesoMedioInicioFemea: 45,
          pesoMedioFimMacho: 75,
          pesoMedioFimFemea: 55,
        },
        {
          nome: "Veterano",
          mesInicio: 97,
          mesFim: 200,
          pesoMedioInicioMacho: 75,
          pesoMedioInicioFemea: 55,
          pesoMedioFimMacho: 75,
          pesoMedioFimFemea: 55,
        },
      ],
    },
    {
      tipo: "Caprino",
      raca: "Kalahari Red",
      origem: "África do Sul",
      pesoNascer: 3.8,
      peso10Meses: 38.0,
      pesoMachoAdulto: 115.0,
      pesoFemeaAdulta: 85.0,
      maturidadeSexual: 6,
      femeaTemLeite: true,
      periodoGestacao: 150,
      quantidadeCabritosParto: 2.8,
      abatePrecoceDias: 85,
      abateConvencionalDias: 160,
      abateTardioDiasMin: 175,
      abateTardioDiasMax: 350,
      pelagemCouro: "curto",
      maxFemeasPorMacho: 50,
      femeasPorMachoIdeal: 35,
      ganhoPesoDiaGramas: 360.0,
      percentualGorduraCarne: 2.4,
      indiceColesterol: "baixo",
      indiceGorduraSaturada: "baixo",
      indiceCalorias: "baixo",
      carneMacia: true,
      carneSaborosa: true,
      carneSucculenta: true,
      fasesGanhoPeso: [
        {
          id: 1,
          nome: "Cabrito",
          mesInicio: 0,
          mesFim: 6,
          pesoMedioInicioMacho: 4,
          pesoMedioInicioFemea: 4,
          pesoMedioFimMacho: 42,
          pesoMedioFimFemea: 38,
        },
        {
          id: 2,
          nome: "Jovem",
          mesInicio: 7,
          mesFim: 13,
          pesoMedioInicioMacho: 42,
          pesoMedioInicioFemea: 38,
          pesoMedioFimMacho: 85,
          pesoMedioFimFemea: 70,
        },
        {
          id: 3,
          nome: "Adulto",
          mesInicio: 14,
          mesFim: 96,
          pesoMedioInicioMacho: 85,
          pesoMedioInicioFemea: 70,
          pesoMedioFimMacho: 115,
          pesoMedioFimFemea: 85,
        },
        {
          nome: "Veterano",
          mesInicio: 97,
          mesFim: 240,
          pesoMedioInicioMacho: 115,
          pesoMedioInicioFemea: 85,
          pesoMedioFimMacho: 115,
          pesoMedioFimFemea: 85,
        },
      ],
    },
    {
      tipo: "Ovino",
      raca: "Suffolk",
      origem: "Inglaterra",
      pesoNascer: 4.5,
      peso10Meses: 50.0,
      pesoMachoAdulto: 130.0,
      pesoFemeaAdulta: 90.0,
      maturidadeSexual: 8,
      femeaTemLeite: true,
      periodoGestacao: 150,
      quantidadeCabritosParto: 1.7,
      abatePrecoceDias: 90,
      abateConvencionalDias: 170,
      abateTardioDiasMin: 190,
      abateTardioDiasMax: 420,
      pelagemCouro: "médio",
      maxFemeasPorMacho: 35,
      femeasPorMachoIdeal: 20,
      ganhoPesoDiaGramas: 400.0,
      percentualGorduraCarne: 3.5,
      indiceColesterol: "baixo",
      indiceGorduraSaturada: "médio",
      indiceCalorias: "médio",
      carneMacia: true,
      carneSaborosa: true,
      carneSucculenta: true,
      fasesGanhoPeso: [
        {
          id: 1,
          nome: "Cordeiro",
          mesInicio: 0,
          mesFim: 6,
          pesoMedioInicioMacho: 5,
          pesoMedioInicioFemea: 4,
          pesoMedioFimMacho: 50,
          pesoMedioFimFemea: 45,
        },
        {
          id: 2,
          nome: "Borrego",
          mesInicio: 7,
          mesFim: 12,
          pesoMedioInicioMacho: 50,
          pesoMedioInicioFemea: 45,
          pesoMedioFimMacho: 90,
          pesoMedioFimFemea: 70,
        },
        {
          id: 3,
          nome: "Adulto",
          mesInicio: 13,
          mesFim: 96,
          pesoMedioInicioMacho: 90,
          pesoMedioInicioFemea: 70,
          pesoMedioFimMacho: 130,
          pesoMedioFimFemea: 90,
        },
        {
          nome: "Veterano",
          mesInicio: 97,
          mesFim: 180,
          pesoMedioInicioMacho: 130,
          pesoMedioInicioFemea: 90,
          pesoMedioFimMacho: 130,
          pesoMedioFimFemea: 90,
        },
      ],
    },
    {
      tipo: "Ovino",
      raca: "Texel",
      origem: "Holanda",
      pesoNascer: 4.8,
      peso10Meses: 48.0,
      pesoMachoAdulto: 110.0,
      pesoFemeaAdulta: 75.0,
      maturidadeSexual: 8,
      femeaTemLeite: true,
      periodoGestacao: 150,
      quantidadeCabritosParto: 1.9,
      abatePrecoceDias: 95,
      abateConvencionalDias: 175,
      abateTardioDiasMin: 195,
      abateTardioDiasMax: 400,
      pelagemCouro: "médio",
      maxFemeasPorMacho: 35,
      femeasPorMachoIdeal: 22,
      ganhoPesoDiaGramas: 350.0,
      percentualGorduraCarne: 3.0,
      indiceColesterol: "baixo",
      indiceGorduraSaturada: "baixo",
      indiceCalorias: "médio",
      carneMacia: true,
      carneSaborosa: true,
      carneSucculenta: true,
      fasesGanhoPeso: [
        {
          id: 1,
          nome: "Cordeiro",
          mesInicio: 0,
          mesFim: 6,
          pesoMedioInicioMacho: 5,
          pesoMedioInicioFemea: 4,
          pesoMedioFimMacho: 48,
          pesoMedioFimFemea: 42,
        },
        {
          id: 2,
          nome: "Borrego",
          mesInicio: 7,
          mesFim: 12,
          pesoMedioInicioMacho: 48,
          pesoMedioInicioFemea: 42,
          pesoMedioFimMacho: 80,
          pesoMedioFimFemea: 60,
        },
        {
          id: 3,
          nome: "Adulto",
          mesInicio: 13,
          mesFim: 96,
          pesoMedioInicioMacho: 80,
          pesoMedioInicioFemea: 60,
          pesoMedioFimMacho: 110,
          pesoMedioFimFemea: 75,
        },
        {
          nome: "Veterano",
          mesInicio: 97,
          mesFim: 180,
          pesoMedioInicioMacho: 110,
          pesoMedioInicioFemea: 75,
          pesoMedioFimMacho: 110,
          pesoMedioFimFemea: 75,
        },
      ],
    },
    {
      tipo: "Bovino",
      raca: "Brahman",
      origem: "Estados Unidos/Índia",
      pesoNascer: 30.0,
      peso10Meses: 270.0,
      pesoMachoAdulto: 850.0,
      pesoFemeaAdulta: 580.0,
      maturidadeSexual: 26,
      femeaTemLeite: true,
      periodoGestacao: 290,
      quantidadeCabritosParto: 1.0,
      abatePrecoceDias: 480,
      abateConvencionalDias: 750,
      abateTardioDiasMin: 950,
      abateTardioDiasMax: 1900,
      pelagemCouro: "curto",
      maxFemeasPorMacho: 30,
      femeasPorMachoIdeal: 18,
      ganhoPesoDiaGramas: 1150.0,
      percentualGorduraCarne: 4.8,
      indiceColesterol: "médio",
      indiceGorduraSaturada: "médio",
      indiceCalorias: "alto",
      carneMacia: true,
      carneSaborosa: true,
      carneSucculenta: true,
      fasesGanhoPeso: [
        {
          id: 1,
          nome: "Bezerro",
          mesInicio: 0,
          mesFim: 12,
          pesoMedioInicioMacho: 30,
          pesoMedioInicioFemea: 28,
          pesoMedioFimMacho: 270,
          pesoMedioFimFemea: 240,
        },
        {
          id: 2,
          nome: "Novilho",
          mesInicio: 13,
          mesFim: 32,
          pesoMedioInicioMacho: 270,
          pesoMedioInicioFemea: 240,
          pesoMedioFimMacho: 580,
          pesoMedioFimFemea: 480,
        },
        {
          id: 3,
          nome: "Adulto",
          mesInicio: 33,
          mesFim: 120,
          pesoMedioInicioMacho: 580,
          pesoMedioInicioFemea: 480,
          pesoMedioFimMacho: 850,
          pesoMedioFimFemea: 580,
        },
        {
          nome: "Veterano",
          mesInicio: 121,
          mesFim: 240,
          pesoMedioInicioMacho: 850,
          pesoMedioInicioFemea: 580,
          pesoMedioFimMacho: 850,
          pesoMedioFimFemea: 580,
        },
      ],
    },
    {
      tipo: "Bovino",
      raca: "Hereford",
      origem: "Inglaterra",
      pesoNascer: 38.0,
      peso10Meses: 340.0,
      pesoMachoAdulto: 950.0,
      pesoFemeaAdulta: 680.0,
      maturidadeSexual: 16,
      femeaTemLeite: true,
      periodoGestacao: 285,
      quantidadeCabritosParto: 1.0,
      abatePrecoceDias: 380,
      abateConvencionalDias: 620,
      abateTardioDiasMin: 750,
      abateTardioDiasMax: 1500,
      pelagemCouro: "curto",
      maxFemeasPorMacho: 25,
      femeasPorMachoIdeal: 15,
      ganhoPesoDiaGramas: 1500.0,
      percentualGorduraCarne: 7.0,
      indiceColesterol: "médio",
      indiceGorduraSaturada: "alto",
      indiceCalorias: "alto",
      carneMacia: true,
      carneSaborosa: true,
      carneSucculenta: true,
      fasesGanhoPeso: [
        {
          id: 1,
          nome: "Bezerro",
          mesInicio: 0,
          mesFim: 12,
          pesoMedioInicioMacho: 38,
          pesoMedioInicioFemea: 35,
          pesoMedioFimMacho: 340,
          pesoMedioFimFemea: 300,
        },
        {
          id: 2,
          nome: "Novilho",
          mesInicio: 13,
          mesFim: 20,
          pesoMedioInicioMacho: 340,
          pesoMedioInicioFemea: 300,
          pesoMedioFimMacho: 680,
          pesoMedioFimFemea: 550,
        },
        {
          id: 3,
          nome: "Adulto",
          mesInicio: 21,
          mesFim: 120,
          pesoMedioInicioMacho: 680,
          pesoMedioInicioFemea: 550,
          pesoMedioFimMacho: 950,
          pesoMedioFimFemea: 680,
        },
        {
          nome: "Veterano",
          mesInicio: 121,
          mesFim: 200,
          pesoMedioInicioMacho: 950,
          pesoMedioInicioFemea: 680,
          pesoMedioFimMacho: 950,
          pesoMedioFimFemea: 680,
        },
      ],
    },
    {
      tipo: "Suíno",
      raca: "Duroc",
      origem: "Estados Unidos",
      pesoNascer: 1.5,
      peso10Meses: 190.0,
      pesoMachoAdulto: 380.0,
      pesoFemeaAdulta: 320.0,
      maturidadeSexual: 6,
      femeaTemLeite: true,
      periodoGestacao: 114,
      quantidadeCabritosParto: 10.5,
      abatePrecoceDias: 85,
      abateConvencionalDias: 170,
      abateTardioDiasMin: 190,
      abateTardioDiasMax: 280,
      pelagemCouro: "curto",
      maxFemeasPorMacho: 12,
      femeasPorMachoIdeal: 8,
      ganhoPesoDiaGramas: 850.0,
      percentualGorduraCarne: 7.5,
      indiceColesterol: "alto",
      indiceGorduraSaturada: "alto",
      indiceCalorias: "alto",
      carneMacia: true,
      carneSaborosa: true,
      carneSucculenta: true,
      fasesGanhoPeso: [
        {
          id: 1,
          nome: "Leitão",
          mesInicio: 0,
          mesFim: 2,
          pesoMedioInicioMacho: 1,
          pesoMedioInicioFemea: 1,
          pesoMedioFimMacho: 28,
          pesoMedioFimFemea: 25,
        },
        {
          id: 2,
          nome: "Crescimento",
          mesInicio: 3,
          mesFim: 6,
          pesoMedioInicioMacho: 28,
          pesoMedioInicioFemea: 25,
          pesoMedioFimMacho: 110,
          pesoMedioFimFemea: 95,
        },
        {
          id: 3,
          nome: "Terminação",
          mesInicio: 7,
          mesFim: 12,
          pesoMedioInicioMacho: 110,
          pesoMedioInicioFemea: 95,
          pesoMedioFimMacho: 280,
          pesoMedioFimFemea: 240,
        },
        {
          nome: "Adulto",
          mesInicio: 13,
          mesFim: 60,
          pesoMedioInicioMacho: 280,
          pesoMedioInicioFemea: 240,
          pesoMedioFimMacho: 380,
          pesoMedioFimFemea: 320,
        },
      ],
    },
    {
      tipo: "Suíno",
      raca: "Hampshire",
      origem: "Inglaterra",
      pesoNascer: 1.6,
      peso10Meses: 200.0,
      pesoMachoAdulto: 360.0,
      pesoFemeaAdulta: 310.0,
      maturidadeSexual: 6,
      femeaTemLeite: true,
      periodoGestacao: 114,
      quantidadeCabritosParto: 10.8,
      abatePrecoceDias: 88,
      abateConvencionalDias: 175,
      abateTardioDiasMin: 195,
      abateTardioDiasMax: 285,
      pelagemCouro: "curto",
      maxFemeasPorMacho: 14,
      femeasPorMachoIdeal: 9,
      ganhoPesoDiaGramas: 820.0,
      percentualGorduraCarne: 7.8,
      indiceColesterol: "alto",
      indiceGorduraSaturada: "alto",
      indiceCalorias: "alto",
      carneMacia: true,
      carneSaborosa: true,
      carneSucculenta: true,
      fasesGanhoPeso: [
        {
          id: 1,
          nome: "Leitão",
          mesInicio: 0,
          mesFim: 2,
          pesoMedioInicioMacho: 2,
          pesoMedioInicioFemea: 2,
          pesoMedioFimMacho: 30,
          pesoMedioFimFemea: 27,
        },
        {
          id: 2,
          nome: "Crescimento",
          mesInicio: 3,
          mesFim: 6,
          pesoMedioInicioMacho: 30,
          pesoMedioInicioFemea: 27,
          pesoMedioFimMacho: 115,
          pesoMedioFimFemea: 100,
        },
        {
          id: 3,
          nome: "Terminação",
          mesInicio: 7,
          mesFim: 12,
          pesoMedioInicioMacho: 115,
          pesoMedioInicioFemea: 100,
          pesoMedioFimMacho: 270,
          pesoMedioFimFemea: 235,
        },
        {
          nome: "Adulto",
          mesInicio: 13,
          mesFim: 60,
          pesoMedioInicioMacho: 270,
          pesoMedioInicioFemea: 235,
          pesoMedioFimMacho: 360,
          pesoMedioFimFemea: 310,
        },
      ],
    },
    {
      tipo: "Equino",
      raca: "Mangalarga Marchador",
      origem: "Brasil",
      pesoNascer: 40.0,
      peso10Meses: 350.0,
      pesoMachoAdulto: 480.0,
      pesoFemeaAdulta: 420.0,
      maturidadeSexual: 30,
      femeaTemLeite: true,
      periodoGestacao: 340,
      quantidadeCabritosParto: 1.0,
      abatePrecoceDias: 0,
      abateConvencionalDias: 0,
      abateTardioDiasMin: 0,
      abateTardioDiasMax: 0,
      pelagemCouro: "curto",
      maxFemeasPorMacho: 15,
      femeasPorMachoIdeal: 8,
      ganhoPesoDiaGramas: 950.0,
      percentualGorduraCarne: 0.0,
      indiceColesterol: "baixo",
      indiceGorduraSaturada: "baixo",
      indiceCalorias: "baixo",
      carneMacia: false,
      carneSaborosa: false,
      carneSucculenta: false,
      fasesGanhoPeso: [
        {
          id: 1,
          nome: "Potro",
          mesInicio: 0,
          mesFim: 12,
          pesoMedioInicioMacho: 40,
          pesoMedioInicioFemea: 38,
          pesoMedioFimMacho: 350,
          pesoMedioFimFemea: 320,
        },
        {
          id: 2,
          nome: "Jovem",
          mesInicio: 13,
          mesFim: 42,
          pesoMedioInicioMacho: 350,
          pesoMedioInicioFemea: 320,
          pesoMedioFimMacho: 440,
          pesoMedioFimFemea: 390,
        },
        {
          id: 3,
          nome: "Adulto",
          mesInicio: 43,
          mesFim: 240,
          pesoMedioInicioMacho: 440,
          pesoMedioInicioFemea: 390,
          pesoMedioFimMacho: 480,
          pesoMedioFimFemea: 420,
        },
        {
          nome: "Veterano",
          mesInicio: 241,
          mesFim: 360,
          pesoMedioInicioMacho: 480,
          pesoMedioInicioFemea: 420,
          pesoMedioFimMacho: 480,
          pesoMedioFimFemea: 420,
        },
      ],
    },
    {
      tipo: "Caprino",
      raca: "Toggenburg",
      origem: "Suíça",
      pesoNascer: 3.6,
      peso10Meses: 30.0,
      pesoMachoAdulto: 70.0,
      pesoFemeaAdulta: 50.0,
      maturidadeSexual: 8,
      femeaTemLeite: true,
      periodoGestacao: 150,
      quantidadeCabritosParto: 2.1,
      abatePrecoceDias: 115,
      abateConvencionalDias: 185,
      abateTardioDiasMin: 210,
      abateTardioDiasMax: 420,
      pelagemCouro: "médio",
      maxFemeasPorMacho: 40,
      femeasPorMachoIdeal: 25,
      ganhoPesoDiaGramas: 230.0,
      percentualGorduraCarne: 3.2,
      indiceColesterol: "baixo",
      indiceGorduraSaturada: "baixo",
      indiceCalorias: "baixo",
      carneMacia: true,
      carneSaborosa: true,
      carneSucculenta: true,
      fasesGanhoPeso: [
        {
          id: 1,
          nome: "Cabrito",
          mesInicio: 0,
          mesFim: 6,
          pesoMedioInicioMacho: 4,
          pesoMedioInicioFemea: 4,
          pesoMedioFimMacho: 28,
          pesoMedioFimFemea: 25,
        },
        {
          id: 2,
          nome: "Jovem",
          mesInicio: 7,
          mesFim: 12,
          pesoMedioInicioMacho: 28,
          pesoMedioInicioFemea: 25,
          pesoMedioFimMacho: 50,
          pesoMedioFimFemea: 40,
        },
        {
          id: 3,
          nome: "Adulto",
          mesInicio: 13,
          mesFim: 96,
          pesoMedioInicioMacho: 50,
          pesoMedioInicioFemea: 40,
          pesoMedioFimMacho: 70,
          pesoMedioFimFemea: 50,
        },
        {
          nome: "Veterano",
          mesInicio: 97,
          mesFim: 200,
          pesoMedioInicioMacho: 70,
          pesoMedioInicioFemea: 50,
          pesoMedioFimMacho: 70,
          pesoMedioFimFemea: 50,
        },
      ],
    },
    {
      tipo: "Caprino",
      raca: "Savana",
      origem: "África do Sul",
      pesoNascer: 4.2,
      peso10Meses: 42.0,
      pesoMachoAdulto: 125.0,
      pesoFemeaAdulta: 90.0,
      maturidadeSexual: 6,
      femeaTemLeite: true,
      periodoGestacao: 150,
      quantidadeCabritosParto: 2.7,
      abatePrecoceDias: 80,
      abateConvencionalDias: 155,
      abateTardioDiasMin: 170,
      abateTardioDiasMax: 340,
      pelagemCouro: "curto",
      maxFemeasPorMacho: 55,
      femeasPorMachoIdeal: 40,
      ganhoPesoDiaGramas: 380.0,
      percentualGorduraCarne: 2.3,
      indiceColesterol: "baixo",
      indiceGorduraSaturada: "baixo",
      indiceCalorias: "baixo",
      carneMacia: true,
      carneSaborosa: true,
      carneSucculenta: true,
      fasesGanhoPeso: [
        {
          id: 1,
          nome: "Cabrito",
          mesInicio: 0,
          mesFim: 6,
          pesoMedioInicioMacho: 4,
          pesoMedioInicioFemea: 4,
          pesoMedioFimMacho: 45,
          pesoMedioFimFemea: 42,
        },
        {
          id: 2,
          nome: "Jovem",
          mesInicio: 7,
          mesFim: 13,
          pesoMedioInicioMacho: 45,
          pesoMedioInicioFemea: 42,
          pesoMedioFimMacho: 90,
          pesoMedioFimFemea: 75,
        },
        {
          id: 3,
          nome: "Adulto",
          mesInicio: 14,
          mesFim: 96,
          pesoMedioInicioMacho: 90,
          pesoMedioInicioFemea: 75,
          pesoMedioFimMacho: 125,
          pesoMedioFimFemea: 90,
        },
        {
          nome: "Veterano",
          mesInicio: 97,
          mesFim: 240,
          pesoMedioInicioMacho: 125,
          pesoMedioInicioFemea: 90,
          pesoMedioFimMacho: 125,
          pesoMedioFimFemea: 90,
        },
      ],
    },
    {
      tipo: "Ovino",
      raca: "Hampshire Down",
      origem: "Inglaterra",
      pesoNascer: 4.3,
      peso10Meses: 47.0,
      pesoMachoAdulto: 115.0,
      pesoFemeaAdulta: 80.0,
      maturidadeSexual: 8,
      femeaTemLeite: true,
      periodoGestacao: 150,
      quantidadeCabritosParto: 1.8,
      abatePrecoceDias: 95,
      abateConvencionalDias: 175,
      abateTardioDiasMin: 195,
      abateTardioDiasMax: 410,
      pelagemCouro: "médio",
      maxFemeasPorMacho: 35,
      femeasPorMachoIdeal: 22,
      ganhoPesoDiaGramas: 360.0,
      percentualGorduraCarne: 3.3,
      indiceColesterol: "baixo",
      indiceGorduraSaturada: "médio",
      indiceCalorias: "médio",
      carneMacia: true,
      carneSaborosa: true,
      carneSucculenta: true,
      fasesGanhoPeso: [
        {
          id: 1,
          nome: "Cordeiro",
          mesInicio: 0,
          mesFim: 6,
          pesoMedioInicioMacho: 4,
          pesoMedioInicioFemea: 4,
          pesoMedioFimMacho: 47,
          pesoMedioFimFemea: 42,
        },
        {
          id: 2,
          nome: "Borrego",
          mesInicio: 7,
          mesFim: 12,
          pesoMedioInicioMacho: 47,
          pesoMedioInicioFemea: 42,
          pesoMedioFimMacho: 85,
          pesoMedioFimFemea: 65,
        },
        {
          id: 3,
          nome: "Adulto",
          mesInicio: 13,
          mesFim: 96,
          pesoMedioInicioMacho: 85,
          pesoMedioInicioFemea: 65,
          pesoMedioFimMacho: 115,
          pesoMedioFimFemea: 80,
        },
        {
          nome: "Veterano",
          mesInicio: 97,
          mesFim: 180,
          pesoMedioInicioMacho: 115,
          pesoMedioInicioFemea: 80,
          pesoMedioFimMacho: 115,
          pesoMedioFimFemea: 80,
        },
      ],
    },
    {
      tipo: "Ovino",
      raca: "Ile de France",
      origem: "França",
      pesoNascer: 5.0,
      peso10Meses: 52.0,
      pesoMachoAdulto: 140.0,
      pesoFemeaAdulta: 95.0,
      maturidadeSexual: 8,
      femeaTemLeite: true,
      periodoGestacao: 150,
      quantidadeCabritosParto: 2.0,
      abatePrecoceDias: 85,
      abateConvencionalDias: 165,
      abateTardioDiasMin: 185,
      abateTardioDiasMax: 430,
      pelagemCouro: "longo",
      maxFemeasPorMacho: 30,
      femeasPorMachoIdeal: 18,
      ganhoPesoDiaGramas: 420.0,
      percentualGorduraCarne: 3.8,
      indiceColesterol: "baixo",
      indiceGorduraSaturada: "médio",
      indiceCalorias: "médio",
      carneMacia: true,
      carneSaborosa: true,
      carneSucculenta: true,
      fasesGanhoPeso: [
        {
          id: 1,
          nome: "Cordeiro",
          mesInicio: 0,
          mesFim: 6,
          pesoMedioInicioMacho: 5,
          pesoMedioInicioFemea: 5,
          pesoMedioFimMacho: 52,
          pesoMedioFimFemea: 48,
        },
        {
          id: 2,
          nome: "Borrego",
          mesInicio: 7,
          mesFim: 12,
          pesoMedioInicioMacho: 52,
          pesoMedioInicioFemea: 48,
          pesoMedioFimMacho: 100,
          pesoMedioFimFemea: 75,
        },
        {
          id: 3,
          nome: "Adulto",
          mesInicio: 13,
          mesFim: 96,
          pesoMedioInicioMacho: 100,
          pesoMedioInicioFemea: 75,
          pesoMedioFimMacho: 140,
          pesoMedioFimFemea: 95,
        },
        {
          nome: "Veterano",
          mesInicio: 97,
          mesFim: 180,
          pesoMedioInicioMacho: 140,
          pesoMedioInicioFemea: 95,
          pesoMedioFimMacho: 140,
          pesoMedioFimFemea: 95,
        },
      ],
    },
    {
      tipo: "Bovino",
      raca: "Simental",
      origem: "Suíça",
      pesoNascer: 42.0,
      peso10Meses: 360.0,
      pesoMachoAdulto: 1000.0,
      pesoFemeaAdulta: 720.0,
      maturidadeSexual: 16,
      femeaTemLeite: true,
      periodoGestacao: 285,
      quantidadeCabritosParto: 1.0,
      abatePrecoceDias: 360,
      abateConvencionalDias: 600,
      abateTardioDiasMin: 720,
      abateTardioDiasMax: 1400,
      pelagemCouro: "curto",
      maxFemeasPorMacho: 25,
      femeasPorMachoIdeal: 15,
      ganhoPesoDiaGramas: 1600.0,
      percentualGorduraCarne: 6.8,
      indiceColesterol: "médio",
      indiceGorduraSaturada: "alto",
      indiceCalorias: "alto",
      carneMacia: true,
      carneSaborosa: true,
      carneSucculenta: true,
      fasesGanhoPeso: [
        {
          id: 1,
          nome: "Bezerro",
          mesInicio: 0,
          mesFim: 12,
          pesoMedioInicioMacho: 42,
          pesoMedioInicioFemea: 38,
          pesoMedioFimMacho: 360,
          pesoMedioFimFemea: 320,
        },
        {
          id: 2,
          nome: "Novilho",
          mesInicio: 13,
          mesFim: 20,
          pesoMedioInicioMacho: 360,
          pesoMedioInicioFemea: 320,
          pesoMedioFimMacho: 720,
          pesoMedioFimFemea: 580,
        },
        {
          id: 3,
          nome: "Adulto",
          mesInicio: 21,
          mesFim: 120,
          pesoMedioInicioMacho: 720,
          pesoMedioInicioFemea: 580,
          pesoMedioFimMacho: 1000,
          pesoMedioFimFemea: 720,
        },
        {
          nome: "Veterano",
          mesInicio: 121,
          mesFim: 200,
          pesoMedioInicioMacho: 1000,
          pesoMedioInicioFemea: 720,
          pesoMedioFimMacho: 1000,
          pesoMedioFimFemea: 720,
        },
      ],
    },
    {
      tipo: "Bovino",
      raca: "Charolês",
      origem: "França",
      pesoNascer: 45.0,
      peso10Meses: 380.0,
      pesoMachoAdulto: 1100.0,
      pesoFemeaAdulta: 750.0,
      maturidadeSexual: 16,
      femeaTemLeite: true,
      periodoGestacao: 285,
      quantidadeCabritosParto: 1.0,
      abatePrecoceDias: 340,
      abateConvencionalDias: 580,
      abateTardioDiasMin: 700,
      abateTardioDiasMax: 1300,
      pelagemCouro: "curto",
      maxFemeasPorMacho: 22,
      femeasPorMachoIdeal: 12,
      ganhoPesoDiaGramas: 1700.0,
      percentualGorduraCarne: 7.2,
      indiceColesterol: "médio",
      indiceGorduraSaturada: "alto",
      indiceCalorias: "alto",
      carneMacia: true,
      carneSaborosa: true,
      carneSucculenta: true,
      fasesGanhoPeso: [
        {
          id: 1,
          nome: "Bezerro",
          mesInicio: 0,
          mesFim: 12,
          pesoMedioInicioMacho: 45,
          pesoMedioInicioFemea: 42,
          pesoMedioFimMacho: 380,
          pesoMedioFimFemea: 340,
        },
        {
          id: 2,
          nome: "Novilho",
          mesInicio: 13,
          mesFim: 19,
          pesoMedioInicioMacho: 380,
          pesoMedioInicioFemea: 340,
          pesoMedioFimMacho: 750,
          pesoMedioFimFemea: 600,
        },
        {
          id: 3,
          nome: "Adulto",
          mesInicio: 20,
          mesFim: 120,
          pesoMedioInicioMacho: 750,
          pesoMedioInicioFemea: 600,
          pesoMedioFimMacho: 1100,
          pesoMedioFimFemea: 750,
        },
        {
          nome: "Veterano",
          mesInicio: 121,
          mesFim: 200,
          pesoMedioInicioMacho: 1100,
          pesoMedioInicioFemea: 750,
          pesoMedioFimMacho: 1100,
          pesoMedioFimFemea: 750,
        },
      ],
    },
    {
      tipo: "Suíno",
      raca: "Landrace",
      origem: "Dinamarca",
      pesoNascer: 1.3,
      peso10Meses: 175.0,
      pesoMachoAdulto: 330.0,
      pesoFemeaAdulta: 280.0,
      maturidadeSexual: 6,
      femeaTemLeite: true,
      periodoGestacao: 114,
      quantidadeCabritosParto: 12.0,
      abatePrecoceDias: 92,
      abateConvencionalDias: 185,
      abateTardioDiasMin: 205,
      abateTardioDiasMax: 310,
      pelagemCouro: "curto",
      maxFemeasPorMacho: 16,
      femeasPorMachoIdeal: 11,
      ganhoPesoDiaGramas: 780.0,
      percentualGorduraCarne: 7.2,
      indiceColesterol: "alto",
      indiceGorduraSaturada: "alto",
      indiceCalorias: "alto",
      carneMacia: true,
      carneSaborosa: true,
      carneSucculenta: true,
      fasesGanhoPeso: [
        {
          id: 1,
          nome: "Leitão",
          mesInicio: 0,
          mesFim: 2,
          pesoMedioInicioMacho: 1,
          pesoMedioInicioFemea: 1,
          pesoMedioFimMacho: 24,
          pesoMedioFimFemea: 21,
        },
        {
          id: 2,
          nome: "Crescimento",
          mesInicio: 3,
          mesFim: 6,
          pesoMedioInicioMacho: 24,
          pesoMedioInicioFemea: 21,
          pesoMedioFimMacho: 95,
          pesoMedioFimFemea: 85,
        },
        {
          id: 3,
          nome: "Terminação",
          mesInicio: 7,
          mesFim: 12,
          pesoMedioInicioMacho: 95,
          pesoMedioInicioFemea: 85,
          pesoMedioFimMacho: 240,
          pesoMedioFimFemea: 210,
        },
        {
          nome: "Adulto",
          mesInicio: 13,
          mesFim: 60,
          pesoMedioInicioMacho: 240,
          pesoMedioInicioFemea: 210,
          pesoMedioFimMacho: 330,
          pesoMedioFimFemea: 280,
        },
      ],
    },
    {
      tipo: "Suíno",
      raca: "Pietrain",
      origem: "Bélgica",
      pesoNascer: 1.7,
      peso10Meses: 195.0,
      pesoMachoAdulto: 350.0,
      pesoFemeaAdulta: 290.0,
      maturidadeSexual: 6,
      femeaTemLeite: true,
      periodoGestacao: 114,
      quantidadeCabritosParto: 9.8,
      abatePrecoceDias: 80,
      abateConvencionalDias: 165,
      abateTardioDiasMin: 185,
      abateTardioDiasMax: 270,
      pelagemCouro: "curto",
      maxFemeasPorMacho: 12,
      femeasPorMachoIdeal: 7,
      ganhoPesoDiaGramas: 900.0,
      percentualGorduraCarne: 6.5,
      indiceColesterol: "alto",
      indiceGorduraSaturada: "alto",
      indiceCalorias: "alto",
      carneMacia: true,
      carneSaborosa: true,
      carneSucculenta: true,
      fasesGanhoPeso: [
        {
          id: 1,
          nome: "Leitão",
          mesInicio: 0,
          mesFim: 2,
          pesoMedioInicioMacho: 2,
          pesoMedioInicioFemea: 2,
          pesoMedioFimMacho: 32,
          pesoMedioFimFemea: 28,
        },
        {
          id: 2,
          nome: "Crescimento",
          mesInicio: 3,
          mesFim: 6,
          pesoMedioInicioMacho: 32,
          pesoMedioInicioFemea: 28,
          pesoMedioFimMacho: 120,
          pesoMedioFimFemea: 105,
        },
        {
          id: 3,
          nome: "Terminação",
          mesInicio: 7,
          mesFim: 12,
          pesoMedioInicioMacho: 120,
          pesoMedioInicioFemea: 105,
          pesoMedioFimMacho: 270,
          pesoMedioFimFemea: 230,
        },
        {
          nome: "Adulto",
          mesInicio: 13,
          mesFim: 60,
          pesoMedioInicioMacho: 270,
          pesoMedioInicioFemea: 230,
          pesoMedioFimMacho: 350,
          pesoMedioFimFemea: 290,
        },
      ],
    },
    {
      tipo: "Equino",
      raca: "Crioulo",
      origem: "Uruguai/Argentina/Brasil",
      pesoNascer: 38.0,
      peso10Meses: 320.0,
      pesoMachoAdulto: 450.0,
      pesoFemeaAdulta: 400.0,
      maturidadeSexual: 36,
      femeaTemLeite: true,
      periodoGestacao: 340,
      quantidadeCabritosParto: 1.0,
      abatePrecoceDias: 0,
      abateConvencionalDias: 0,
      abateTardioDiasMin: 0,
      abateTardioDiasMax: 0,
      pelagemCouro: "curto",
      maxFemeasPorMacho: 18,
      femeasPorMachoIdeal: 10,
      ganhoPesoDiaGramas: 900.0,
      percentualGorduraCarne: 0.0,
      indiceColesterol: "baixo",
      indiceGorduraSaturada: "baixo",
      indiceCalorias: "baixo",
      carneMacia: false,
      carneSaborosa: false,
      carneSucculenta: false,
      fasesGanhoPeso: [
        {
          id: 1,
          nome: "Potro",
          mesInicio: 0,
          mesFim: 12,
          pesoMedioInicioMacho: 38,
          pesoMedioInicioFemea: 35,
          pesoMedioFimMacho: 320,
          pesoMedioFimFemea: 290,
        },
        {
          id: 2,
          nome: "Jovem",
          mesInicio: 13,
          mesFim: 48,
          pesoMedioInicioMacho: 320,
          pesoMedioInicioFemea: 290,
          pesoMedioFimMacho: 410,
          pesoMedioFimFemea: 370,
        },
        {
          id: 3,
          nome: "Adulto",
          mesInicio: 49,
          mesFim: 240,
          pesoMedioInicioMacho: 410,
          pesoMedioInicioFemea: 370,
          pesoMedioFimMacho: 450,
          pesoMedioFimFemea: 400,
        },
        {
          nome: "Veterano",
          mesInicio: 241,
          mesFim: 420,
          pesoMedioInicioMacho: 450,
          pesoMedioInicioFemea: 400,
          pesoMedioFimMacho: 450,
          pesoMedioFimFemea: 400,
        },
      ],
    },
    {
      tipo: "Caprino",
      raca: "Anglonubiano",
      origem: "Brasil/Inglaterra/Egito",
      pesoNascer: 3.9,
      peso10Meses: 29.0,
      pesoMachoAdulto: 85.0,
      pesoFemeaAdulta: 62.0,
      maturidadeSexual: 8,
      femeaTemLeite: true,
      periodoGestacao: 150,
      quantidadeCabritosParto: 2.1,
      abatePrecoceDias: 125,
      abateConvencionalDias: 190,
      abateTardioDiasMin: 210,
      abateTardioDiasMax: 420,
      pelagemCouro: "curto",
      maxFemeasPorMacho: 38,
      femeasPorMachoIdeal: 24,
      ganhoPesoDiaGramas: 270.0,
      percentualGorduraCarne: 3.1,
      indiceColesterol: "baixo",
      indiceGorduraSaturada: "baixo",
      indiceCalorias: "baixo",
      carneMacia: true,
      carneSaborosa: true,
      carneSucculenta: true,
      fasesGanhoPeso: [
        {
          id: 1,
          nome: "Cabrito",
          mesInicio: 0,
          mesFim: 6,
          pesoMedioInicioMacho: 4,
          pesoMedioInicioFemea: 4,
          pesoMedioFimMacho: 33,
          pesoMedioFimFemea: 30,
        },
        {
          id: 2,
          nome: "Jovem",
          mesInicio: 7,
          mesFim: 12,
          pesoMedioInicioMacho: 33,
          pesoMedioInicioFemea: 30,
          pesoMedioFimMacho: 60,
          pesoMedioFimFemea: 50,
        },
        {
          id: 3,
          nome: "Adulto",
          mesInicio: 13,
          mesFim: 96,
          pesoMedioInicioMacho: 60,
          pesoMedioInicioFemea: 50,
          pesoMedioFimMacho: 85,
          pesoMedioFimFemea: 62,
        },
        {
          nome: "Veterano",
          mesInicio: 97,
          mesFim: 200,
          pesoMedioInicioMacho: 85,
          pesoMedioInicioFemea: 62,
          pesoMedioFimMacho: 85,
          pesoMedioFimFemea: 62,
        },
      ],
    },
    {
      tipo: "Caprino",
      raca: "Parda Alpina",
      origem: "França/Suíça",
      pesoNascer: 3.7,
      peso10Meses: 31.0,
      pesoMachoAdulto: 73.0,
      pesoFemeaAdulta: 53.0,
      maturidadeSexual: 7,
      femeaTemLeite: true,
      periodoGestacao: 150,
      quantidadeCabritosParto: 2.4,
      abatePrecoceDias: 105,
      abateConvencionalDias: 175,
      abateTardioDiasMin: 195,
      abateTardioDiasMax: 390,
      pelagemCouro: "médio",
      maxFemeasPorMacho: 42,
      femeasPorMachoIdeal: 28,
      ganhoPesoDiaGramas: 245.0,
      percentualGorduraCarne: 2.9,
      indiceColesterol: "baixo",
      indiceGorduraSaturada: "baixo",
      indiceCalorias: "baixo",
      carneMacia: true,
      carneSaborosa: true,
      carneSucculenta: true,
      fasesGanhoPeso: [
        {
          id: 1,
          nome: "Cabrito",
          mesInicio: 0,
          mesFim: 6,
          pesoMedioInicioMacho: 4,
          pesoMedioInicioFemea: 4,
          pesoMedioFimMacho: 29,
          pesoMedioFimFemea: 27,
        },
        {
          id: 2,
          nome: "Jovem",
          mesInicio: 7,
          mesFim: 12,
          pesoMedioInicioMacho: 29,
          pesoMedioInicioFemea: 27,
          pesoMedioFimMacho: 52,
          pesoMedioFimFemea: 43,
        },
        {
          id: 3,
          nome: "Adulto",
          mesInicio: 13,
          mesFim: 96,
          pesoMedioInicioMacho: 52,
          pesoMedioInicioFemea: 43,
          pesoMedioFimMacho: 73,
          pesoMedioFimFemea: 53,
        },
        {
          nome: "Veterano",
          mesInicio: 97,
          mesFim: 200,
          pesoMedioInicioMacho: 73,
          pesoMedioInicioFemea: 53,
          pesoMedioFimMacho: 73,
          pesoMedioFimFemea: 53,
        },
      ],
    },
    {
      tipo: "Caprino",
      raca: "Canindé",
      origem: "Brasil",
      pesoNascer: 2.8,
      peso10Meses: 25.0,
      pesoMachoAdulto: 55.0,
      pesoFemeaAdulta: 40.0,
      maturidadeSexual: 9,
      femeaTemLeite: true,
      periodoGestacao: 150,
      quantidadeCabritosParto: 1.8,
      abatePrecoceDias: 140,
      abateConvencionalDias: 210,
      abateTardioDiasMin: 240,
      abateTardioDiasMax: 450,
      pelagemCouro: "curto",
      maxFemeasPorMacho: 30,
      femeasPorMachoIdeal: 18,
      ganhoPesoDiaGramas: 190.0,
      percentualGorduraCarne: 2.6,
      indiceColesterol: "baixo",
      indiceGorduraSaturada: "baixo",
      indiceCalorias: "baixo",
      carneMacia: true,
      carneSaborosa: true,
      carneSucculenta: true,
      fasesGanhoPeso: [
        {
          id: 1,
          nome: "Cabrito",
          mesInicio: 0,
          mesFim: 6,
          pesoMedioInicioMacho: 3,
          pesoMedioInicioFemea: 3,
          pesoMedioFimMacho: 22,
          pesoMedioFimFemea: 20,
        },
        {
          id: 2,
          nome: "Jovem",
          mesInicio: 7,
          mesFim: 12,
          pesoMedioInicioMacho: 22,
          pesoMedioInicioFemea: 20,
          pesoMedioFimMacho: 40,
          pesoMedioFimFemea: 32,
        },
        {
          id: 3,
          nome: "Adulto",
          mesInicio: 13,
          mesFim: 96,
          pesoMedioInicioMacho: 40,
          pesoMedioInicioFemea: 32,
          pesoMedioFimMacho: 55,
          pesoMedioFimFemea: 40,
        },
        {
          nome: "Veterano",
          mesInicio: 97,
          mesFim: 240,
          pesoMedioInicioMacho: 55,
          pesoMedioInicioFemea: 40,
          pesoMedioFimMacho: 55,
          pesoMedioFimFemea: 40,
        },
      ],
    },
    {
      tipo: "Ovino",
      raca: "White Dorper",
      origem: "África do Sul",
      pesoNascer: 4.0,
      peso10Meses: 43.0,
      pesoMachoAdulto: 115.0,
      pesoFemeaAdulta: 80.0,
      maturidadeSexual: 8,
      femeaTemLeite: true,
      periodoGestacao: 150,
      quantidadeCabritosParto: 1.7,
      abatePrecoceDias: 105,
      abateConvencionalDias: 185,
      abateTardioDiasMin: 205,
      abateTardioDiasMax: 460,
      pelagemCouro: "misto",
      maxFemeasPorMacho: 38,
      femeasPorMachoIdeal: 24,
      ganhoPesoDiaGramas: 370.0,
      percentualGorduraCarne: 3.1,
      indiceColesterol: "baixo",
      indiceGorduraSaturada: "baixo",
      indiceCalorias: "médio",
      carneMacia: true,
      carneSaborosa: true,
      carneSucculenta: true,
      fasesGanhoPeso: [
        {
          id: 1,
          nome: "Cordeiro",
          mesInicio: 0,
          mesFim: 6,
          pesoMedioInicioMacho: 4,
          pesoMedioInicioFemea: 4,
          pesoMedioFimMacho: 43,
          pesoMedioFimFemea: 38,
        },
        {
          id: 2,
          nome: "Borrego",
          mesInicio: 7,
          mesFim: 12,
          pesoMedioInicioMacho: 43,
          pesoMedioInicioFemea: 38,
          pesoMedioFimMacho: 78,
          pesoMedioFimFemea: 62,
        },
        {
          id: 3,
          nome: "Adulto",
          mesInicio: 13,
          mesFim: 96,
          pesoMedioInicioMacho: 78,
          pesoMedioInicioFemea: 62,
          pesoMedioFimMacho: 115,
          pesoMedioFimFemea: 80,
        },
        {
          nome: "Veterano",
          mesInicio: 97,
          mesFim: 180,
          pesoMedioInicioMacho: 115,
          pesoMedioInicioFemea: 80,
          pesoMedioFimMacho: 115,
          pesoMedioFimFemea: 80,
        },
      ],
    },
    {
      tipo: "Bovino",
      raca: "Limousin",
      origem: "França",
      pesoNascer: 40.0,
      peso10Meses: 350.0,
      pesoMachoAdulto: 1000.0,
      pesoFemeaAdulta: 700.0,
      maturidadeSexual: 16,
      femeaTemLeite: true,
      periodoGestacao: 285,
      quantidadeCabritosParto: 1.0,
      abatePrecoceDias: 350,
      abateConvencionalDias: 590,
      abateTardioDiasMin: 710,
      abateTardioDiasMax: 1350,
      pelagemCouro: "curto",
      maxFemeasPorMacho: 24,
      femeasPorMachoIdeal: 14,
      ganhoPesoDiaGramas: 1650.0,
      percentualGorduraCarne: 6.8,
      indiceColesterol: "médio",
      indiceGorduraSaturada: "alto",
      indiceCalorias: "alto",
      carneMacia: true,
      carneSaborosa: true,
      carneSucculenta: true,
      fasesGanhoPeso: [
        {
          id: 1,
          nome: "Bezerro",
          mesInicio: 0,
          mesFim: 12,
          pesoMedioInicioMacho: 40,
          pesoMedioInicioFemea: 37,
          pesoMedioFimMacho: 350,
          pesoMedioFimFemea: 310,
        },
        {
          id: 2,
          nome: "Novilho",
          mesInicio: 13,
          mesFim: 20,
          pesoMedioInicioMacho: 350,
          pesoMedioInicioFemea: 310,
          pesoMedioFimMacho: 700,
          pesoMedioFimFemea: 560,
        },
        {
          id: 3,
          nome: "Adulto",
          mesInicio: 21,
          mesFim: 120,
          pesoMedioInicioMacho: 700,
          pesoMedioInicioFemea: 560,
          pesoMedioFimMacho: 1000,
          pesoMedioFimFemea: 700,
        },
        {
          nome: "Veterano",
          mesInicio: 121,
          mesFim: 200,
          pesoMedioInicioMacho: 1000,
          pesoMedioInicioFemea: 700,
          pesoMedioFimMacho: 1000,
          pesoMedioFimFemea: 700,
        },
      ],
    },
    {
      tipo: "Bovino",
      raca: "Gir",
      origem: "Índia",
      pesoNascer: 28.0,
      peso10Meses: 260.0,
      pesoMachoAdulto: 750.0,
      pesoFemeaAdulta: 500.0,
      maturidadeSexual: 30,
      femeaTemLeite: true,
      periodoGestacao: 290,
      quantidadeCabritosParto: 1.0,
      abatePrecoceDias: 480,
      abateConvencionalDias: 750,
      abateTardioDiasMin: 920,
      abateTardioDiasMax: 1850,
      pelagemCouro: "curto",
      maxFemeasPorMacho: 32,
      femeasPorMachoIdeal: 22,
      ganhoPesoDiaGramas: 1100.0,
      percentualGorduraCarne: 4.5,
      indiceColesterol: "médio",
      indiceGorduraSaturada: "médio",
      indiceCalorias: "alto",
      carneMacia: true,
      carneSaborosa: true,
      carneSucculenta: true,
      fasesGanhoPeso: [
        {
          id: 1,
          nome: "Bezerro",
          mesInicio: 0,
          mesFim: 12,
          pesoMedioInicioMacho: 28,
          pesoMedioInicioFemea: 26,
          pesoMedioFimMacho: 260,
          pesoMedioFimFemea: 230,
        },
        {
          id: 2,
          nome: "Novilho",
          mesInicio: 13,
          mesFim: 36,
          pesoMedioInicioMacho: 260,
          pesoMedioInicioFemea: 230,
          pesoMedioFimMacho: 500,
          pesoMedioFimFemea: 400,
        },
        {
          id: 3,
          nome: "Adulto",
          mesInicio: 37,
          mesFim: 120,
          pesoMedioInicioMacho: 500,
          pesoMedioInicioFemea: 400,
          pesoMedioFimMacho: 750,
          pesoMedioFimFemea: 500,
        },
        {
          nome: "Veterano",
          mesInicio: 121,
          mesFim: 240,
          pesoMedioInicioMacho: 750,
          pesoMedioInicioFemea: 500,
          pesoMedioFimMacho: 750,
          pesoMedioFimFemea: 500,
        },
      ],
    },
    {
      tipo: "Bovino",
      raca: "Guzeratá",
      origem: "Índia/Brasil",
      pesoNascer: 30.0,
      peso10Meses: 270.0,
      pesoMachoAdulto: 780.0,
      pesoFemeaAdulta: 520.0,
      maturidadeSexual: 28,
      femeaTemLeite: true,
      periodoGestacao: 290,
      quantidadeCabritosParto: 1.0,
      abatePrecoceDias: 460,
      abateConvencionalDias: 730,
      abateTardioDiasMin: 900,
      abateTardioDiasMax: 1800,
      pelagemCouro: "curto",
      maxFemeasPorMacho: 30,
      femeasPorMachoIdeal: 20,
      ganhoPesoDiaGramas: 1150.0,
      percentualGorduraCarne: 4.8,
      indiceColesterol: "médio",
      indiceGorduraSaturada: "médio",
      indiceCalorias: "alto",
      carneMacia: true,
      carneSaborosa: true,
      carneSucculenta: true,
      fasesGanhoPeso: [
        {
          id: 1,
          nome: "Bezerro",
          mesInicio: 0,
          mesFim: 12,
          pesoMedioInicioMacho: 30,
          pesoMedioInicioFemea: 28,
          pesoMedioFimMacho: 270,
          pesoMedioFimFemea: 240,
        },
        {
          id: 2,
          nome: "Novilho",
          mesInicio: 13,
          mesFim: 34,
          pesoMedioInicioMacho: 270,
          pesoMedioInicioFemea: 240,
          pesoMedioFimMacho: 520,
          pesoMedioFimFemea: 420,
        },
        {
          id: 3,
          nome: "Adulto",
          mesInicio: 35,
          mesFim: 120,
          pesoMedioInicioMacho: 520,
          pesoMedioInicioFemea: 420,
          pesoMedioFimMacho: 780,
          pesoMedioFimFemea: 520,
        },
        {
          nome: "Veterano",
          mesInicio: 121,
          mesFim: 240,
          pesoMedioInicioMacho: 780,
          pesoMedioInicioFemea: 520,
          pesoMedioFimMacho: 780,
          pesoMedioFimFemea: 520,
        },
      ],
    },
    {
      tipo: "Bovino",
      raca: "Senepol",
      origem: "Santa Cruz",
      pesoNascer: 34.0,
      peso10Meses: 300.0,
      pesoMachoAdulto: 850.0,
      pesoFemeaAdulta: 580.0,
      maturidadeSexual: 20,
      femeaTemLeite: true,
      periodoGestacao: 285,
      quantidadeCabritosParto: 1.0,
      abatePrecoceDias: 420,
      abateConvencionalDias: 680,
      abateTardioDiasMin: 820,
      abateTardioDiasMax: 1650,
      pelagemCouro: "curto",
      maxFemeasPorMacho: 28,
      femeasPorMachoIdeal: 18,
      ganhoPesoDiaGramas: 1300.0,
      percentualGorduraCarne: 5.2,
      indiceColesterol: "médio",
      indiceGorduraSaturada: "médio",
      indiceCalorias: "alto",
      carneMacia: true,
      carneSaborosa: true,
      carneSucculenta: true,
      fasesGanhoPeso: [
        {
          id: 1,
          nome: "Bezerro",
          mesInicio: 0,
          mesFim: 12,
          pesoMedioInicioMacho: 34,
          pesoMedioInicioFemea: 32,
          pesoMedioFimMacho: 300,
          pesoMedioFimFemea: 270,
        },
        {
          id: 2,
          nome: "Novilho",
          mesInicio: 13,
          mesFim: 24,
          pesoMedioInicioMacho: 300,
          pesoMedioInicioFemea: 270,
          pesoMedioFimMacho: 580,
          pesoMedioFimFemea: 480,
        },
        {
          id: 3,
          nome: "Adulto",
          mesInicio: 25,
          mesFim: 120,
          pesoMedioInicioMacho: 580,
          pesoMedioInicioFemea: 480,
          pesoMedioFimMacho: 850,
          pesoMedioFimFemea: 580,
        },
        {
          nome: "Veterano",
          mesInicio: 121,
          mesFim: 200,
          pesoMedioInicioMacho: 850,
          pesoMedioInicioFemea: 580,
          pesoMedioFimMacho: 850,
          pesoMedioFimFemea: 580,
        },
      ],
    },
    {
      tipo: "Suíno",
      raca: "Berkshire",
      origem: "Inglaterra",
      pesoNascer: 1.5,
      peso10Meses: 185.0,
      pesoMachoAdulto: 340.0,
      pesoFemeaAdulta: 290.0,
      maturidadeSexual: 6,
      femeaTemLeite: true,
      periodoGestacao: 114,
      quantidadeCabritosParto: 10.2,
      abatePrecoceDias: 85,
      abateConvencionalDias: 170,
      abateTardioDiasMin: 190,
      abateTardioDiasMax: 275,
      pelagemCouro: "curto",
      maxFemeasPorMacho: 13,
      femeasPorMachoIdeal: 8,
      ganhoPesoDiaGramas: 830.0,
      percentualGorduraCarne: 7.8,
      indiceColesterol: "alto",
      indiceGorduraSaturada: "alto",
      indiceCalorias: "alto",
      carneMacia: true,
      carneSaborosa: true,
      carneSucculenta: true,
      fasesGanhoPeso: [
        {
          id: 1,
          nome: "Leitão",
          mesInicio: 0,
          mesFim: 2,
          pesoMedioInicioMacho: 2,
          pesoMedioInicioFemea: 2,
          pesoMedioFimMacho: 26,
          pesoMedioFimFemea: 23,
        },
        {
          id: 2,
          nome: "Crescimento",
          mesInicio: 3,
          mesFim: 6,
          pesoMedioInicioMacho: 26,
          pesoMedioInicioFemea: 23,
          pesoMedioFimMacho: 105,
          pesoMedioFimFemea: 92,
        },
        {
          id: 3,
          nome: "Terminação",
          mesInicio: 7,
          mesFim: 12,
          pesoMedioInicioMacho: 105,
          pesoMedioInicioFemea: 92,
          pesoMedioFimMacho: 260,
          pesoMedioFimFemea: 225,
        },
        {
          nome: "Adulto",
          mesInicio: 13,
          mesFim: 60,
          pesoMedioInicioMacho: 260,
          pesoMedioInicioFemea: 225,
          pesoMedioFimMacho: 340,
          pesoMedioFimFemea: 290,
        },
      ],
    },
    {
      tipo: "Suíno",
      raca: "Chester White",
      origem: "Estados Unidos",
      pesoNascer: 1.4,
      peso10Meses: 180.0,
      pesoMachoAdulto: 360.0,
      pesoFemeaAdulta: 310.0,
      maturidadeSexual: 6,
      femeaTemLeite: true,
      periodoGestacao: 114,
      quantidadeCabritosParto: 11.5,
      abatePrecoceDias: 88,
      abateConvencionalDias: 175,
      abateTardioDiasMin: 195,
      abateTardioDiasMax: 290,
      pelagemCouro: "curto",
      maxFemeasPorMacho: 15,
      femeasPorMachoIdeal: 10,
      ganhoPesoDiaGramas: 810.0,
      percentualGorduraCarne: 8.2,
      indiceColesterol: "alto",
      indiceGorduraSaturada: "alto",
      indiceCalorias: "alto",
      carneMacia: true,
      carneSaborosa: true,
      carneSucculenta: true,
      fasesGanhoPeso: [
        {
          id: 1,
          nome: "Leitão",
          mesInicio: 0,
          mesFim: 2,
          pesoMedioInicioMacho: 1,
          pesoMedioInicioFemea: 1,
          pesoMedioFimMacho: 26,
          pesoMedioFimFemea: 23,
        },
        {
          id: 2,
          nome: "Crescimento",
          mesInicio: 3,
          mesFim: 6,
          pesoMedioInicioMacho: 26,
          pesoMedioInicioFemea: 23,
          pesoMedioFimMacho: 100,
          pesoMedioFimFemea: 88,
        },
        {
          id: 3,
          nome: "Terminação",
          mesInicio: 7,
          mesFim: 12,
          pesoMedioInicioMacho: 100,
          pesoMedioInicioFemea: 88,
          pesoMedioFimMacho: 270,
          pesoMedioFimFemea: 235,
        },
        {
          nome: "Adulto",
          mesInicio: 13,
          mesFim: 60,
          pesoMedioInicioMacho: 270,
          pesoMedioInicioFemea: 235,
          pesoMedioFimMacho: 360,
          pesoMedioFimFemea: 310,
        },
      ],
    },
    {
      tipo: "Equino",
      raca: "Campolina",
      origem: "Brasil",
      pesoNascer: 42.0,
      peso10Meses: 360.0,
      pesoMachoAdulto: 520.0,
      pesoFemeaAdulta: 460.0,
      maturidadeSexual: 30,
      femeaTemLeite: true,
      periodoGestacao: 340,
      quantidadeCabritosParto: 1.0,
      abatePrecoceDias: 0,
      abateConvencionalDias: 0,
      abateTardioDiasMin: 0,
      abateTardioDiasMax: 0,
      pelagemCouro: "curto",
      maxFemeasPorMacho: 16,
      femeasPorMachoIdeal: 9,
      ganhoPesoDiaGramas: 980.0,
      percentualGorduraCarne: 0.0,
      indiceColesterol: "baixo",
      indiceGorduraSaturada: "baixo",
      indiceCalorias: "baixo",
      carneMacia: false,
      carneSaborosa: false,
      carneSucculenta: false,
      fasesGanhoPeso: [
        {
          id: 1,
          nome: "Potro",
          mesInicio: 0,
          mesFim: 12,
          pesoMedioInicioMacho: 42,
          pesoMedioInicioFemea: 40,
          pesoMedioFimMacho: 360,
          pesoMedioFimFemea: 330,
        },
        {
          id: 2,
          nome: "Jovem",
          mesInicio: 13,
          mesFim: 40,
          pesoMedioInicioMacho: 360,
          pesoMedioInicioFemea: 330,
          pesoMedioFimMacho: 470,
          pesoMedioFimFemea: 420,
        },
        {
          id: 3,
          nome: "Adulto",
          mesInicio: 41,
          mesFim: 240,
          pesoMedioInicioMacho: 470,
          pesoMedioInicioFemea: 420,
          pesoMedioFimMacho: 520,
          pesoMedioFimFemea: 460,
        },
        {
          nome: "Veterano",
          mesInicio: 241,
          mesFim: 360,
          pesoMedioInicioMacho: 520,
          pesoMedioInicioFemea: 460,
          pesoMedioFimMacho: 520,
          pesoMedioFimFemea: 460,
        },
      ],
    },
    {
      tipo: "Equino",
      raca: "Puro Sangue Inglês",
      origem: "Inglaterra",
      pesoNascer: 50.0,
      peso10Meses: 420.0,
      pesoMachoAdulto: 580.0,
      pesoFemeaAdulta: 510.0,
      maturidadeSexual: 24,
      femeaTemLeite: true,
      periodoGestacao: 340,
      quantidadeCabritosParto: 1.0,
      abatePrecoceDias: 0,
      abateConvencionalDias: 0,
      abateTardioDiasMin: 0,
      abateTardioDiasMax: 0,
      pelagemCouro: "curto",
      maxFemeasPorMacho: 18,
      femeasPorMachoIdeal: 10,
      ganhoPesoDiaGramas: 1200.0,
      percentualGorduraCarne: 0.0,
      indiceColesterol: "baixo",
      indiceGorduraSaturada: "baixo",
      indiceCalorias: "baixo",
      carneMacia: false,
      carneSaborosa: false,
      carneSucculenta: false,
      fasesGanhoPeso: [
        {
          id: 1,
          nome: "Potro",
          mesInicio: 0,
          mesFim: 12,
          pesoMedioInicioMacho: 50,
          pesoMedioInicioFemea: 47,
          pesoMedioFimMacho: 420,
          pesoMedioFimFemea: 380,
        },
        {
          id: 2,
          nome: "Jovem",
          mesInicio: 13,
          mesFim: 30,
          pesoMedioInicioMacho: 420,
          pesoMedioInicioFemea: 380,
          pesoMedioFimMacho: 530,
          pesoMedioFimFemea: 470,
        },
        {
          id: 3,
          nome: "Adulto",
          mesInicio: 31,
          mesFim: 180,
          pesoMedioInicioMacho: 530,
          pesoMedioInicioFemea: 470,
          pesoMedioFimMacho: 580,
          pesoMedioFimFemea: 510,
        },
        {
          nome: "Veterano",
          mesInicio: 181,
          mesFim: 300,
          pesoMedioInicioMacho: 580,
          pesoMedioInicioFemea: 510,
          pesoMedioFimMacho: 580,
          pesoMedioFimFemea: 510,
        },
      ],
    },
    {
      tipo: "Equino",
      raca: "Paint Horse",
      origem: "Estados Unidos",
      pesoNascer: 46.0,
      peso10Meses: 390.0,
      pesoMachoAdulto: 560.0,
      pesoFemeaAdulta: 490.0,
      maturidadeSexual: 24,
      femeaTemLeite: true,
      periodoGestacao: 340,
      quantidadeCabritosParto: 1.0,
      abatePrecoceDias: 0,
      abateConvencionalDias: 0,
      abateTardioDiasMin: 0,
      abateTardioDiasMax: 0,
      pelagemCouro: "curto",
      maxFemeasPorMacho: 19,
      femeasPorMachoIdeal: 11,
      ganhoPesoDiaGramas: 1150.0,
      percentualGorduraCarne: 0.0,
      indiceColesterol: "baixo",
      indiceGorduraSaturada: "baixo",
      indiceCalorias: "baixo",
      carneMacia: false,
      carneSaborosa: false,
      carneSucculenta: false,
      fasesGanhoPeso: [
        {
          id: 1,
          nome: "Potro",
          mesInicio: 0,
          mesFim: 12,
          pesoMedioInicioMacho: 46,
          pesoMedioInicioFemea: 43,
          pesoMedioFimMacho: 390,
          pesoMedioFimFemea: 360,
        },
        {
          id: 2,
          nome: "Jovem",
          mesInicio: 13,
          mesFim: 32,
          pesoMedioInicioMacho: 390,
          pesoMedioInicioFemea: 360,
          pesoMedioFimMacho: 510,
          pesoMedioFimFemea: 450,
        },
        {
          id: 3,
          nome: "Adulto",
          mesInicio: 33,
          mesFim: 240,
          pesoMedioInicioMacho: 510,
          pesoMedioInicioFemea: 450,
          pesoMedioFimMacho: 560,
          pesoMedioFimFemea: 490,
        },
        {
          nome: "Veterano",
          mesInicio: 241,
          mesFim: 360,
          pesoMedioInicioMacho: 560,
          pesoMedioInicioFemea: 490,
          pesoMedioFimMacho: 560,
          pesoMedioFimFemea: 490,
        },
      ],
    },
    {
      tipo: "Equino",
      raca: "Appaloosa",
      origem: "Estados Unidos",
      pesoNascer: 44.0,
      peso10Meses: 370.0,
      pesoMachoAdulto: 540.0,
      pesoFemeaAdulta: 470.0,
      maturidadeSexual: 26,
      femeaTemLeite: true,
      periodoGestacao: 340,
      quantidadeCabritosParto: 1.0,
      abatePrecoceDias: 0,
      abateConvencionalDias: 0,
      abateTardioDiasMin: 0,
      abateTardioDiasMax: 0,
      pelagemCouro: "curto",
      maxFemeasPorMacho: 17,
      femeasPorMachoIdeal: 10,
      ganhoPesoDiaGramas: 1080.0,
      percentualGorduraCarne: 0.0,
      indiceColesterol: "baixo",
      indiceGorduraSaturada: "baixo",
      indiceCalorias: "baixo",
      carneMacia: false,
      carneSaborosa: false,
      carneSucculenta: false,
      fasesGanhoPeso: [
        {
          id: 1,
          nome: "Potro",
          mesInicio: 0,
          mesFim: 12,
          pesoMedioInicioMacho: 44,
          pesoMedioInicioFemea: 41,
          pesoMedioFimMacho: 370,
          pesoMedioFimFemea: 340,
        },
        {
          id: 2,
          nome: "Jovem",
          mesInicio: 13,
          mesFim: 34,
          pesoMedioInicioMacho: 370,
          pesoMedioInicioFemea: 340,
          pesoMedioFimMacho: 490,
          pesoMedioFimFemea: 430,
        },
        {
          id: 3,
          nome: "Adulto",
          mesInicio: 35,
          mesFim: 240,
          pesoMedioInicioMacho: 490,
          pesoMedioInicioFemea: 430,
          pesoMedioFimMacho: 540,
          pesoMedioFimFemea: 470,
        },
        {
          nome: "Veterano",
          mesInicio: 241,
          mesFim: 360,
          pesoMedioInicioMacho: 540,
          pesoMedioInicioFemea: 470,
          pesoMedioFimMacho: 540,
          pesoMedioFimFemea: 470,
        },
      ],
    },
  ];

  console.log("🌱 Iniciando seed das características das raças...");

  // Primeiro, inserir todas as raças básicas (nome e tipo)
  const racasBasicas = [
    // Caprinos
    { tipo: "Caprino", raca: "Boer" },
    { tipo: "Caprino", raca: "Anglo-Nubiana" },
    { tipo: "Caprino", raca: "Saanen" },
    { tipo: "Caprino", raca: "Alpina" },
    { tipo: "Caprino", raca: "Toggenburg" },
    { tipo: "Caprino", raca: "Anglonubiano" },
    { tipo: "Caprino", raca: "Kalahari Red" },
    { tipo: "Caprino", raca: "Savana" },
    { tipo: "Caprino", raca: "Parda Alpina" },
    { tipo: "Caprino", raca: "Canindé" },

    // Ovinos
    { tipo: "Ovino", raca: "Dorper" },
    { tipo: "Ovino", raca: "Santa Inês" },
    { tipo: "Ovino", raca: "Suffolk" },
    { tipo: "Ovino", raca: "Hampshire Down" },
    { tipo: "Ovino", raca: "Texel" },
    { tipo: "Ovino", raca: "Ile de France" },
    { tipo: "Ovino", raca: "White Dorper" },

    // Bovinos
    { tipo: "Bovino", raca: "Nelore" },
    { tipo: "Bovino", raca: "Angus" },
    { tipo: "Bovino", raca: "Brahman" },
    { tipo: "Bovino", raca: "Hereford" },
    { tipo: "Bovino", raca: "Simental" },
    { tipo: "Bovino", raca: "Charolês" },
    { tipo: "Bovino", raca: "Limousin" },
    { tipo: "Bovino", raca: "Gir" },
    { tipo: "Bovino", raca: "Guzerá" },
    { tipo: "Bovino", raca: "Senepol" },

    // Suínos
    { tipo: "Suíno", raca: "Landrace" },
    { tipo: "Suíno", raca: "Large White" },
    { tipo: "Suíno", raca: "Duroc" },
    { tipo: "Suíno", raca: "Hampshire" },
    { tipo: "Suíno", raca: "Pietrain" },
    { tipo: "Suíno", raca: "Berkshire" },
    { tipo: "Suíno", raca: "Chester White" },

    // Equinos
    { tipo: "Equino", raca: "Quarto de Milha" },
    { tipo: "Equino", raca: "Mangalarga Marchador" },
    { tipo: "Equino", raca: "Crioulo" },
    { tipo: "Equino", raca: "Campolina" },
    { tipo: "Equino", raca: "Puro Sangue Inglês" },
    { tipo: "Equino", raca: "Paint Horse" },
    { tipo: "Equino", raca: "Appaloosa" },
  ];

  // Inserir raças básicas
  for (const { tipo, raca } of racasBasicas) {
    await prisma.racaCaracteristicas.upsert({
      where: {
        tipo_raca: { tipo, raca },
      },
      update: {},
      create: { tipo, raca },
    });
    console.log(`✓ ${tipo} - ${raca} (básico)`);
  }

  // Depois, atualizar com características detalhadas
  for (const racaData of racasCaracteristicas) {
    await prisma.racaCaracteristicas.upsert({
      where: {
        tipo_raca: {
          tipo: racaData.tipo,
          raca: racaData.raca,
        },
      },
      update: racaData,
      create: racaData,
    });
    console.log(`✅ ${racaData.tipo} - ${racaData.raca} (detalhado)`);
  }

  console.log(
    `\n✅ ${racasBasicas.length} raças básicas + ${racasCaracteristicas.length} com características detalhadas inseridas com sucesso!`
  );
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
